# ./Dockerfile.frontend
FROM node:20-alpine AS builder
WORKDIR /ui
COPY frontend/package.json frontend/package-lock.json* ./ 
RUN npm ci
COPY frontend ./frontend
RUN npm run build

FROM nginx:1.25-alpine
COPY --from=builder /ui/frontend/dist /usr/share/nginx/html
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
