# ──────────────── FRONTEND IMAGE ────────────────
FROM node:20-alpine AS builder

WORKDIR /frontend
COPY frontend/package*.json ./
RUN npm ci
COPY frontend .
RUN npm run build

# -------- serve with tiny static server ----------
FROM nginx:alpine
COPY --from=builder /frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
