version: "3.9"

services:
  # ---------- database ----------
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # ---------- redis -------------
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "60", "1"]
    volumes:
      - redisdata:/data
    restart: unless-stopped

  # ---------- backend -----------
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "${BACKEND_PORT}:8008"
    restart: unless-stopped

  # ----------- frontend ---------
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file: .env
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:80"
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
