version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-humanitas}
      POSTGRES_USER: ${POSTGRES_USER:-humanitas}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeit}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env            # your DB_URL, JWT_SECRET, etc.
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
